// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfI654he2eGdmYpBfQdR44J-5hcXTA5yI',
    appId: '1:748533568693:web:b572f346678b6bf388dafc',
    messagingSenderId: '748533568693',
    projectId: 'veterinaria-friendly-pets',
    authDomain: 'veterinaria-friendly-pets.firebaseapp.com',
    storageBucket: 'veterinaria-friendly-pets.appspot.com',
    measurementId: 'G-47ZS1ZR684',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRHHipMyI0x1XMwGhpAEUhXWwBhOnQuw',
    appId: '1:748533568693:android:bd19a2d272e2bc2588dafc',
    messagingSenderId: '748533568693',
    projectId: 'veterinaria-friendly-pets',
    storageBucket: 'veterinaria-friendly-pets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZC7_Nb3_Gb8uHoCwALR78J3R2TfkqWhU',
    appId: '1:748533568693:ios:fad1d464490e6b3e88dafc',
    messagingSenderId: '748533568693',
    projectId: 'veterinaria-friendly-pets',
    storageBucket: 'veterinaria-friendly-pets.appspot.com',
    iosClientId: '748533568693-caevgc6bp6kcqi27ur7jripsqno4pkgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoVeterinaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZC7_Nb3_Gb8uHoCwALR78J3R2TfkqWhU',
    appId: '1:748533568693:ios:fad1d464490e6b3e88dafc',
    messagingSenderId: '748533568693',
    projectId: 'veterinaria-friendly-pets',
    storageBucket: 'veterinaria-friendly-pets.appspot.com',
    iosClientId: '748533568693-caevgc6bp6kcqi27ur7jripsqno4pkgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoVeterinaria',
  );
}
